INSERT INTO OAUTH_CLIENT_DETAILS(CLIENT_ID, RESOURCE_IDS, CLIENT_SECRET, SCOPE, AUTHORIZED_GRANT_TYPES, AUTHORITIES, ACCESS_TOKEN_VALIDITY, REFRESH_TOKEN_VALIDITY)
	VALUES ('BPD-CLIENT', 'BPD-API',
	'$2a$04$ACvIOlbOOsrxbn/b5d66be7jFbkXPvBkzD2heppGvBf.0VCwDe0i.',
	'read,write', 'password,authorization_code,refresh_token,implicit', 'USER', 10800, 2592000);